### ISSUE TITLE
Can you please upload all the files for one semester？

### ISSUE THREAD

**Issue by hufydsg** [TongWu/IT5004-EnterpriseSysArch#1]
Hello, I am attending IT5004 in 24/25 sem1 and I see that the folder you uploaded seems to be only a part of the documents, can you please upload all the files for one semester? Would appreciate it if you could upload them, thanks!

**Comment by TongWu** [comment]
Hi @hufydsg, thanks for opening issue for this repo! I uploaded the remaining lectures and tutorials for this class and I will close this issue.
